management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
