management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
